---
title: "RStudio Team System Admin :: <b>CHEATSHEET</b>"
author: "Andrie de Vries"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_collapse: true
    toc_float: true
    toc_depth: 4
css: include/styles.css

---

<!-- ribbon from https://codepo8.github.io/css-fork-on-github-ribbon/ -->

<style>#forkongithub a{background:#FCECCC;color:#000;text-decoration:none;font-family:arial,sans-serif;text-align:center;font-weight:bold;padding:5px 40px;font-size:1rem;line-height:2rem;position:relative;transition:0.5s;}#forkongithub a:hover{background:#DFECF7;color:#000;}#forkongithub a::before,#forkongithub a::after{content:"";width:100%;display:block;position:absolute;top:1px;left:0;height:1px;background:#fff;}#forkongithub a::after{bottom:1px;top:auto;}@media screen and (min-width:1000px){#forkongithub{position:absolute;display:block;top:0;right:0;width:200px;overflow:hidden;height:200px;z-index:9999;}#forkongithub a{width:200px;position:absolute;top:45px;right:-45px;transform:rotate(45deg);-webkit-transform:rotate(45deg);-ms-transform:rotate(45deg);-moz-transform:rotate(45deg);-o-transform:rotate(45deg);box-shadow:4px 4px 10px rgba(0,0,0,0.8);}}</style><span id="forkongithub"><a href="https://github.com/sol-eng/sys-admin-cheatsheet">Fork me on GitHub</a></span>


## Documentation

Topic                               | Link
:----                               | :-------------
General                             | https://docs.rstudio.com/
Installing R                        | https://docs.rstudio.com/resources/install-r/
Installing Python                   | https://docs.rstudio.com/resources/install-python/
RStudio Server admin guide          | https://docs.rstudio.com/ide/server-pro/
RStudio Connect admin guide         | https://docs.rstudio.com/connect/admin/
RStudio Package Manager admin guide | https://docs.rstudio.com/rspm/admin/
Pro Drivers                         | https://docs.rstudio.com/pro-drivers/


Pre-requisites:

* [Supported platforms](https://rstudio.com/about/platform-support)
* [Product requirements](https://support.rstudio.com/hc/en-us/articles/360015177453-RStudio-professional-product-requirements)

## Installing R

### Install R from pre-compiled binaries

Recommended best practise is to install R from pre-compiled binaries

https://docs.rstudio.com/resources/install-r/

For example, on Ubuntu 18.04 for R version 3.6.1.

```sh
sudo sed -i.bak "/^#.*deb-src.*universe$/s/^# //g" /etc/apt/sources.list
sudo apt-get update
sudo apt-get install gdebi-core

export R_VERSION=3.6.1

curl -O https://cdn.rstudio.com/r/ubuntu-1804/pkgs/r-${R_VERSION}_1_amd64.deb
sudo gdebi r-${R_VERSION}_1_amd64.deb
```

This script installs into `/opt/R/...`

Verify installation:

```sh
/opt/R/${R_VERSION}/bin/R --version
```


## RStudio Server Pro

Admin guide: https://docs.rstudio.com/ide/server-pro/

### Starting, stopping and restarting

Running the verify installation command:

```sh
sudo rstudio-server stop
sudo rstudio-server verify-installation
sudo rstudio-server start
```

To restart the RSP service and check its status, run these commands (with `sudo` if necessary):

```sh
sudo rstudio-server restart
sudo rstudio-server status
```

### Status

```sh
rstudio-server status
```


### Error logs

The locations of the various server log files:

```sh
ls /var/log/rstudio-server
```

```sh
cat /var/log/rstudio-server/rserver-http-error.log
```

The server log is at:

```sh
tail /var/lib/rstudio-server/monitor/log/rstudio-server.log
```


## RStudio Connect 

Admin guide: https://docs.rstudio.com/connect/admin/

### Config file

```sh
/etc/rstudio-connect/rstudio-connect.gcfg
```

### Systemd vs upstart

Distributions using systemd include Red Hat/CentOS 7, Red Hat/CentOS 8, SUSE 12, Ubuntu 16.04, and Ubuntu 18.04.

* `systemctl start rstudio-connect`


Distributions using Upstart include Red Hat/CentOS 6 and Ubuntu 14.04.

* `start rstudio-connect`

### Starting and stopping

```sh
sudo systemctl start rstudio-connect
sudo systemctl stop rstudio-connect
sudo systemctl restart rstudio-connect
sudo systemctl reload rstudio-connect
```

### Checking status

```sh
sudo systemctl status rstudio-connect
```


### Log files

```sh
sudo tail /var/log/rstudio-connect.log
```


### Get the diagnostics script

```sh
/opt/rstudio-connect/scripts/run-diagnostics.sh
```

## RStudio Package Manager 

Admin guide: https://docs.rstudio.com/rspm/admin/

```sh
sudo systemctl status rstudio-pm
```

Try running the `rspm` command on the server instance where RSPM is installed:

```sh
/opt/rstudio-pm/bin/rspm
```

To save keystrokes when typing RSPM commands, create a command alias for the
`rspm` command:

```sh
echo "alias rspm='/opt/rstudio-pm/bin/rspm'" >> ~/.bashrc
```

If you run the `rspm` command with no arguments, then you'll see a list of
available commands:

```sh
$ rspm
Available Commands:
add         Command to add packages to sources
air-gap     Command to print help for setting up an air-gapped RStudio Package Manager service
archive     Command to archive packages in sources
clear-cran  Command to purge CRAN metadata. Cannot be used if any repos subscribe to CRAN.
create      Commands to create entities
delete      Commands to delete entities
edit        Commands to edit repo name and description
fetch       Command to initiate eager package fetching
help        Help about any command
import      Command to import SSH keys
info        Command to print information about sources and repos
list        Commands to list entities.
logs        Command to retrieve logs for package builds
remove      Command to remove packages from sources
reorder     Command to reorder repo subscriptions to sources
rerun       Command to rerun git-builders
run         Command to run git-builders
subscribe   Command to subscribe repos to sources
sync        Command to initiate an ad-hoc sync of the default cran source
unsubscribe Command to unsubscribe repos from sources
update      Command to update curated-cran sources
```
### Working with CRAN
```sh
sync        Command to initiate an ad-hoc sync of the default cran source
clear-cran  Command to purge CRAN metadata. Cannot be used if any repos subscribe to CRAN.
```
### Manage repositories and sources
```sh
create      Commands to create entities
delete      Commands to delete entities
list        Commands to list entities
update      Command to update curated-cran sources
```
### Manage packages
```sh
add         Command to add packages to sources
archive     Command to archive packages in sources
remove      Command to remove packages from sources
```
### Working with repositories
```sh
edit        Commands to edit repo name and description
reorder     Command to reorder repo subscriptions to sources
subscribe   Command to subscribe repos to sources
unsubscribe Command to unsubscribe repos from sources
```
### Utilities
```sh
air-gap     Command to print help for setting up an air-gapped RStudio Package Manager service
fetch       Command to initiate eager package fetching
help        Help about any command
import      Command to import SSH keys
info        Command to print information about sources and repos
logs        Command to retrieve logs for package builds
```
### System health check
You have various methods to check the health of your RSPM instance:
1. View the RSPM application logs:
    ```sh
    sudo cat /var/log/rstudio-pm.log
    ```
2. View the RSPM access logs:
    ```sh
    sudo cat /var/log/rstudio-pm.access.log
    ```
3. Check the status of your RSPM license:
    ```sh
    sudo /opt/rstudio-pm/bin/license-manager status
    ```
4. Run RSPM diagnostics:
    ```sh
    sudo /opt/rstudio-pm/bin/run-diagnostics
    ```
   View diagnostics output:
     ```sh
     cat rspm_diagnostics-report.txt
     ```
## License manager
### View license status:
```sh
sudo /opt/rstudio-pm/bin/license-manager status
```
Activate license:
```sh
sudo /opt/rstudio-pm/bin/license-manager activate LICENSE_KEY
```
List of available commands:
```sh
sudo /opt/rstudio-pm/bin/license-manager
```
```sh
Supported commands: acquire-lease, acquire-lease-verbose, activate,
activate-offline, activate-offline-request, begin-evaluation-offline,
...
```
### Expired license
- Things to try:
  - Check time and time zone  `timedatectl`
  - Resync if needed, e.g. `sudo hwclock -w`
  - Restart

### Deactivating a license
    
Deactivation tool: http://apps.rstudio.com/deactivate-license/



## Pro Drivers 

Documentation overview: https://docs.rstudio.com/pro-drivers/

Driver locations:

```sh
cat /etc/odbc.ini 
cat /etc/odbcinst.ini
```



## Troubleshooting

### Troubleshooting R

Almost all RStudio products depend on R being installed successfully to run.
  
* Look for errors related to R in the server logs
  
Can R be launched manually and can the user's code be run in R without any errors?

How was R installed? 

* From source or [pre-compiled binaries](https://docs.rstudio.com/resources/install-r/)? If so, were all correct flags and capabilities set?  

```sh
grep configure R_HOME/etc/Makeconf
```
    
Are all necessary dependencies installed? 


```sh
apt-get build-dep r-base
yum-builddep R
```

Are the permissions set correctly to allow `r-x` by all?      

```sh
namei -l /path/to/R
```

Are there multiple versions of R on the system?

```sh
apt-get install mlocate
updatedb
locate libR.so
```


### Troubleshooting configuration

Look for any errors in the startup.  You can view the live log during startup using:
  
```sh
tail -f /path/to/log
```

Read through the admin guides and make sure you have the correct formatting

Make sure you're on the right version of the product compared to the admin guide!


### Troubleshooting authentication

Difficult for RStudio Support to troubleshoot as it depends on external configuration values unknown to us.

Does it work outside of the RStudio product?

* Often possible to copy over working setup from other systems or services.
* For RStudio Server Pro, the`pamtester` utility lets you test outside RStudio systems.
  
```sh
sudo /usr/lib/rstudio-server/bin/pamtester \
--verbose rstudio <username> authenticate
```
  
Check server log files including `access.log` files.

Check connections to any external authentication providers

* Kerberos, Active Directory, etc.


## General Linux tips 

### OS version

What OS are you using?

```sh
cat /etc/*-release
```

or

```sh
uname -a
```

### Export environment variable to PATH

```sh
export PATH=$PATH:/opt/R/3.5.0/bin
```



